version: '3.5'

volumes:
  postgres_volume:

services:
  postgres:
    hostname: postgres
    image: postgres:14-alpine
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready"]
    ports:
      - "5432:5432"
    networks:
      - product-catalog-network

  product-catalog-service:
    restart: always
    build: .
    depends_on:
      - postgres
    ports:
      - "${GRPC_PORT:-5001}:${GRPC_PORT:-5001}"
      - "${HTTP_PORT:-8080}:${HTTP_PORT:-8080}"
      - "${SWAGGER_PORT:-8090}:${SWAGGER_PORT:-8090}"
    networks:
      - product-catalog-network

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    env_file:
      - .env
    networks:
      - product-catalog-network

networks:
  product-catalog-network: