version: '3.5'

volumes:
  postgres_volume:

networks:
  product_catalog_network:
    external: true

services:
  pg:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    image: "cr.selcloud.ru/krul/postgres:14-alpine"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready"]
    ports:
      - "5432:5432"
    networks:
      - product_catalog_network

  product-catalog-service:
    restart: always
    build: .
    image: "cr.selcloud.ru/krul/product-catalog-service:latest"
    depends_on:
      - pg
    ports:
      - "${GRPC_PORT:-5001}:${GRPC_PORT:-5001}"
      - "${HTTP_PORT:-8080}:${HTTP_PORT:-8080}"
      - "${SWAGGER_PORT:-8090}:${SWAGGER_PORT:-8090}"
    networks:
      - product_catalog_network

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    image: "cr.selcloud.ru/krul/migrator:latest"
    restart: on-failure
    env_file:
      - .env
    networks:
      - product_catalog_network
